% this loads MI and energy data generated by the batch script and makes plots 

gsyn_scale_factors = [1,5,10,15,20];
noise_scale_factors = [0.5,1,1.5,2];

for pp = 1:3;%length(noise_scale_factors)
    noise_scaler = noise_scale_factors(pp);
    
    for p = 1:length(gsyn_scale_factors)
        gsyn_scaler = gsyn_scale_factors(p);
   
        fname2 = ['output/noise_' num2str(noise_scaler) '/gsyn_' num2str(gsyn_scaler) 'MIandEnergySummaryParams.mat'];
        load(fname2);

        MI_data(pp,p) = MI_energy_params(1); 
        Energy_data(pp,p)= MI_energy_params(4);
        
    end
end

EnergyEfficiency = MI_data ./ Energy_data;

xaxis = 2.*gsyn_scale_factors; % to get x axis ticks, 2 = original amplitude of EPSConductance wave

% plots for each noise level
for myplot = 1:length(EnergyEfficiency(:,1))
    
   subplot(3,1,1)
      plot(xaxis,MI_data(myplot,:),'.r')
      xlim([0 60])
      hold on   

   subplot(3,1,2)
      plot(xaxis,Energy_data(myplot,:),'.b')
      hold on   

   subplot(3,1,3)
      plot(xaxis,EnergyEfficiency(myplot,:),'.g')
      hold on   
end



