% this loads MI and energy data generated by the batch script and makes plots 

gsyn_scale_factors = [0,1,5,10,20, 30,40,50,55,75,100];

Excitatory_synapses = [120 160 200 ];
Inhibitory_synapses = 0;
nreps = 500

for pp = 1:length(Excitatory_synapses)
    ExSyns = Excitatory_synapses(pp);
    pp
    for p = 1:length(gsyn_scale_factors)
        gsyn_scaler = gsyn_scale_factors(p);
   p
            % directory and file paths
        basepath = 'Z:\Oliver\attwell_rotation\matlab\mutual_info_neuron\output\';
        
        if exist(basepath,'dir')==0 % checks what machine you're on
            basepath = '/Users/olivergauld/Desktop/present/UCL/R2/attwell_rotation/matlab/mutual_info_neuron/output';
        end
        
        
        datafolder = ['/London_model/' num2str(nreps) 'reps/ExSyn_num' num2str(ExSyns) '/'];
        RawDatafilename = ['RawData_gsyn_' num2str(gsyn_scaler) 'reps' num2str(nreps) '.mat'];
        SummaryFile = ['gsyn_' num2str(gsyn_scaler) 'reps' num2str(nreps) '_SummaryParams.mat'];
    
        my_path = [basepath datafolder RawDatafilename];
        my_path2 = [basepath datafolder SummaryFile];

        load(my_path2);
        
        MI_data(pp,p) = MI_energy_params(1); 
        Energy_data(pp,p)= MI_energy_params(4);
        Hnoise_data(pp,p) = MI_energy_params(3);
        Htotal_data(pp,p) = MI_energy_params(2);

        load(my_path)

        mean_freq_Hz(pp,p) = mean(horzcat(data_store{:,3}));
        mean_energy_oncurrent(pp,p) = mean(horzcat(data_store{:,5}));% this corresponds to atp used on Na current
    end
end

%% calculate various variables for graphing

EnergyEfficiency = MI_data ./ Energy_data; % current and AP atp use

MIperSpike = MI_data ./ mean_freq_Hz;
MIperSpike(isnan(MIperSpike))=0;

Energy_on_current = mean_energy_oncurrent; % ATP used on EPSC

currentEnergyEfficiency = MI_data ./ Energy_on_current;
currentEnergyEfficiency(isnan(currentEnergyEfficiency))=0;
currentEnergyEfficiency(isinf(currentEnergyEfficiency))=0;

% Efficiency measure from Strong paper
CapacityEffiency = MI_data ./ Htotal_data;
CapacityEffiency(isnan(CapacityEffiency))=0;
CapacityEffiency = CapacityEffiency*100;
CapacityEnergyEfficiency = CapacityEffiency ./ Energy_on_current;


xaxis = 2.*gsyn_scale_factors; % to get x axis ticks, 2 = amplitude of non-scaled EPSConductance wave
cc=hsv(length(Excitatory_synapses));

mark = {'-o','-x','-d','-*','-<','->','-o'};

figure(1)
%%% plot as function of gSyn
for myplot = 1:length(EnergyEfficiency(:,1))
    % xaxis is gSyn in nS
    % Mutual Info
    
   subplot(3,3,1)
      plot(xaxis,MI_data(myplot,:),mark{myplot},'color',cc(myplot,:))
      hold on     
      title('Mutual Info')
      ylabel('bits/sec')
      xlabel('gsyn [nS]')
      legend
      
          %AP freq
   subplot(3,3,2)
      plot(xaxis,MIperSpike(myplot,:),mark{myplot},'color',cc(myplot,:))
      hold on  
      title('MI per Spike')
      xlabel('gsyn [nS]')
      ylabel('bits/APspike')    
            
    % Energy
   subplot(3,3,3)
      plot(xaxis,Energy_data(myplot,:),mark{myplot},'color',cc(myplot,:))
      hold on   
      title('ATP (current + APs)')
      ylabel('ATP/sec')
      xlabel('gsyn [nS]')
    % Energy
    
   subplot(3,3,4)
      plot(xaxis,Energy_on_current(myplot,:),mark{myplot},'color',cc(myplot,:))
      hold on   
      title('ATP on EPSCurrent only')
      ylabel('ATP/sec')
      xlabel('gsyn [nS]')

   % MI / Energy
   subplot(3,3,5)
      plot(xaxis,currentEnergyEfficiency(myplot,:),mark{myplot},'color',cc(myplot,:))
      hold on   
      title('Information Efficiency (current energy only)')
      ylabel('bits/ATP')
      xlabel('gsyn [nS]')

       % MI / Energy
   subplot(3,3,6)
      plot(xaxis,EnergyEfficiency(myplot,:),mark{myplot},'color',cc(myplot,:))
      hold on   
      title('Information Efficiency (current + AP energy)')
      ylabel('bits/ATP')
      xlabel('gsyn [nS]')
      

   %AP freq
   subplot(3,3,7)
      plot(xaxis,mean_freq_Hz(myplot,:),mark{myplot},'color',cc(myplot,:))
      hold on  
      title('PostSynaptic (Output) AP freq.')
      xlabel('gsyn [nS]')
      ylabel('Freq. Hz')
      
         %AP freq
   subplot(3,3,8)
      plot(xaxis,CapacityEffiency(myplot,:),mark{myplot},'color',cc(myplot,:))
      hold on  
      title('Capacity Effiency.')
      xlabel('gsyn [nS]')
      ylabel('total capacity')
               
      %AP freq
   subplot(3,3,9)
      plot(xaxis,CapacityEnergyEfficiency(myplot,:),mark{myplot},'color',cc(myplot,:))
      hold on  
      title('Capacity Energy Effiency.')
      xlabel('gsyn [nS]')
      ylabel('units?')
      
end
