% this loads MI and energy data generated by the batch script and makes plots 

gsyn_scale_factors = [1,5,10,15,20,25,30,40,50,70,90,100];
noise_scale_factors = [0.1,0.5,1,1.125,1.25,2];
wordLength = [4 6 7];

for WL = 1:length(wordLength)
    myWL = wordLength(myWL)
    for pp = 1:length(noise_scale_factors)
    noise_scaler = noise_scale_factors(pp);
    
    for p = 1:length(gsyn_scale_factors)
        gsyn_scaler = gsyn_scale_factors(p);
   
        fname2 = ['output/new_noise_model/noisescale_' num2str(noise_scaler) '/gsyn_' num2str(gsyn_scaler) '.mat'];
        load(fname2);

        [MI, Htotal, final_Hnoise] = MI_calculation(data_store(:,1),myWL); % calulates Mutual Info

        fname1 = ['output/new_noise_model_WL_' num2str(myWL) '/noisescale_' num2str(noise_scaler) '/gsyn_' num2str(gsyn_scaler) '.mat'];
        load(fname1)
        
        mean_freq_Hz(pp,p) = mean(horzcat(data_store{:,3}));
        
        
    end
    end
end